ola: clean
	@echo "=================================="
	@echo "         PROGRAMA Bissecao"
	@echo "=================================="
	@echo "- Compilando Bissecao"
	gcc Bissecao.c -o Bissecao
	@echo "- Torna o programa olamundo executásvel"
	chmod +x Bissecao
	@echo "- Executando o programa ola mundo"
	./Bissecao
	@echo "=================================="

clean:
	@echo "===================================="
	@echo "Removendo os programas compilados"
	@echo "===================================="
	@echo "Removendo o programa olamundo"
	rm -f ola
	@echo "===================================="

help:
	@echo "======================"
	@echo "         AJUDA"
	@echo "======================"
	@echo "help		| ajuda"
	@echo "ela		| executar mensagem de texto"
	@echo "clean| apagar codigos compilados"